{% set name = "whitenoise" %}
{% set version = "5.0.1" %}
{% set sha256 = "0f9137f74bd95fa54329ace88d8dc695fbe895369a632e35f7a136e003e41d73" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - python

test:
  imports:
    - whitenoise

about:
  home: https://github.com/evansd/whitenoise
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Radically simplified static file serving for Python web apps'
  description: |
    With a couple of lines of config WhiteNoise allows your web app to serve its own static files, 
    making it a self-contained unit that can be deployed anywhere without relying on nginx, Amazon 
    S3 or any other external service. (Especially useful on Heroku, OpenShift and other PaaS providers.)
    It's designed to work nicely with a CDN for high-traffic sites so you don't have to sacrifice 
    performance to benefit from simplicity. WhiteNoise works with any WSGI-compatible app but has some 
    special auto-configuration features for Django.
  doc_url: http://whitenoise.evans.io/en/stable/
  dev_url: https://github.com/evansd/whitenoise

extra:
  recipe-maintainers:
    - cshaley
    - sannykr
